apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  SERVICE: {{ .Chart.Name }}
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema }}
  POSTGRES_USER: {{ .Values.postgres.user }}
