apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  labels:
    app: {{ .Chart.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name}}
